apiVersion: v1
kind: Secret
metadata:
  name: onlytodo-argocd
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: "https://github.com/Atom-Pch/OnlyToDo"
  name: "onlytodo-app"
  type: "git"
  username: "github"
  password: "${GITHUB_TOKEN}"
