# This is NOT the main CI pipeline.
# GitLab is used solely as an external cron scheduler to trigger GitHub Actions workflows for daily infra startup/teardown.
# See: .github/workflows/infra-up.yml and infra-down.yml
stages:
  - infra_create
  - infra_destroy

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "schedule"

variables:
  GITHUB_USER: "Atom-Pch"
  GITHUB_REPO: "OnlyToDo"

morning_infra_create:
  stage: infra_create
  image: alpine/curl:8.17.0
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" && $ACTION == "up"
    - if: $CI_PIPELINE_SOURCE == "schedule" && $ACTION == "up"
  script: |
    curl -L \
      -X POST \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer $GITHUB_PAT" \
      -H "X-GitHub-Api-Version: 2026-03-10" \
      https://api.github.com/repos/$GITHUB_USER/$GITHUB_REPO/actions/workflows/infra-up.yml/dispatches \
      -d '{"ref":"main"}'

evening_infra_destroy:
  stage: infra_destroy
  image: alpine/curl:8.17.0
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" && $ACTION == "down"
    - if: $CI_PIPELINE_SOURCE == "schedule" && $ACTION == "down"
  script: |
    curl -L \
       -X POST \
       -H "Accept: application/vnd.github+json" \
       -H "Authorization: Bearer $GITHUB_PAT" \
       -H "X-GitHub-Api-Version: 2026-03-10" \
       https://api.github.com/repos/$GITHUB_USER/$GITHUB_REPO/actions/workflows/infra-down.yml/dispatches \
       -d '{"ref":"main"}'
