apiVersion: v1
kind: ConfigMap
metadata:
  name: ecr-login-script
  namespace: argocd
data:
  ecr-login.sh: |
    #!/bin/sh
    # Fetches the token and formats it as AWS:ey...
    aws ecr get-login-password --region us-east-2 | awk '{print "AWS:" $0}'
