apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: onlytodo-backend-updater
  namespace: argocd
spec:
  writeBackConfig:
    method: "git"
    gitConfig:
      repository: "https://github.com/Atom-Pch/OnlyToDo.git"
      branch: "main"
      writeBackTarget: "helmvalues:values.yml"
  applicationRefs:
    - namePattern: "onlytodo-backend"
      images:
        - alias: "backend"
          imageName: "131912109503.dkr.ecr.us-east-2.amazonaws.com/onlytodo-backend"
          manifestTargets:
            helm:
              name: image.repository
              tag: image.tag
  commonUpdateSettings:
    updateStrategy: "newest-build"
    pullSecret: pullsecret:argocd/aws-ecr-creds
---
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: onlytodo-frontend-updater
  namespace: argocd
spec:
  writeBackConfig:
    method: "git"
    gitConfig:
      repository: "https://github.com/Atom-Pch/OnlyToDo.git"
      branch: "main"
      writeBackTarget: "helmvalues:values.yml"
  applicationRefs:
    - namePattern: "onlytodo-frontend"
      images:
        - alias: "frontend"
          imageName: "131912109503.dkr.ecr.us-east-2.amazonaws.com/onlytodo-frontend"
          manifestTargets:
            helm:
              name: image.repository
              tag: image.tag
  commonUpdateSettings:
    updateStrategy: "newest-build"
    pullSecret: pullsecret:argocd/aws-ecr-creds
