apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onlytodo-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Atom-Pch/OnlyToDo.git
    targetRevision: main
    path: deploy/charts/backend
    helm:
      valueFiles:
        - values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
