apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  # HA
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-sa
      initContainers:
        - name: db-init
          image: postgres:18-alpine
          env:
            # We reuse the exact same environment variables (and secrets!) as your backend
            - name: DB_HOST
              value: "todo-db.c962yekmm5ja.us-east-2.rds.amazonaws.com"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "atom"
            - name: DB_NAME
              value: "todo_db"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-secrets-default
                  key: db_pass
          command:
            - sh
            - -c
            - |
              set -e  # ← exit immediately if any command fails
              echo "Checking if Core Table exists in Database..."
              TABLE_EXISTS=$(psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -tAc \
                "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'users');")

              if [ "$TABLE_EXISTS" = "f" ]; then
                echo "Database was empty. Applying initialization script..."
                psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -f /scripts/init.sql
                echo "Initialization script applied successfully."
              else
                echo "Table found. Skipping."
              fi
          volumeMounts:
            - name: script-volume
              mountPath: /scripts
      containers:
        - name: backend
          # Minikube
          # image: todo-backend:latest
          # imagePullPolicy: Never # Forces Minikube to use the local image
          # ECR
          image: 131912109503.dkr.ecr.us-east-2.amazonaws.com/todo-backend-repo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 9090 # For Prometheus Metrics

          # Resource Requests and Limits
          resources:
            requests:
              memory: 128Mi
              cpu: 256m
            limits:
              memory: 256Mi
              cpu: 512m

          env:
            # Later for EKS, we will move these to ConfigMaps and Secrets!
            - name: DB_HOST
              value: "todo-db.c962yekmm5ja.us-east-2.rds.amazonaws.com"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "atom"
            - name: DB_NAME
              value: "todo_db"
            - name: S3_BUCKET_NAME
              value: "todo-files-131912109503-us-east-2-an"
            - name: AWS_REGION
              value: "us-east-2"
            - name: PORT
              value: "8080"

            # --- SECURE VARIABLES ---
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: todo-secrets-default
                  key: db_pass
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: todo-secrets-default
                  key: jwt_token

          # Readiness and Liveness Probes
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15

      # --- NEW VOLUME FOR THE CONFIGMAP ---
      volumes:
        - name: script-volume
          configMap:
            name: db-init-script

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP # ClusterIP means it's only accessible from inside the K8s cluster
