apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets-default
  namespace: default
type: Opaque
stringData:
  db_pass: "${DB_PASS}"
  jwt_token: "${JWT_TOKEN}"
---
apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets-monitoring
  namespace: monitoring
type: Opaque
stringData:
  admin-user: "${GRAFANA_USER}"
  admin-password: "${GRAFANA_PASS}"
