---
- name: Frontend ECR Push Latest Tag
  hosts: localhost
  gather_facts: false
  vars:
    aws_region: "us-east-2"
    ecr_registry: "131912109503.dkr.ecr.us-east-2.amazonaws.com"
    image_name: "todo-frontend-repo"
    full_image_path: "{{ ecr_registry }}/{{ image_name }}:latest"
    project_directory: "../../frontend"

  tasks:
    - name: Authenticate Docker client to AWS ECR
      ansible.builtin.shell: |
        set -o pipefail
        aws ecr get-login-password --region {{ aws_region }} | docker login --username AWS --password-stdin {{ ecr_registry }}
      args:
        executable: /bin/bash
      register: login_output
      changed_when: "'Login Succeeded' in login_output.stdout"

    - name: Build the Docker image
      ansible.builtin.command: docker build --provenance=false -t {{ image_name }} .
      args:
        chdir: "{{ project_directory }}"
      register: build_output
      changed_when: "'naming to docker.io' not in build_output.stderr"

    - name: Tag the Docker image for ECR
      ansible.builtin.command: docker tag {{ image_name }}:latest {{ full_image_path }}
      changed_when: false

    - name: Push the Docker image to AWS ECR
      ansible.builtin.command: docker push {{ full_image_path }}
      register: push_output
      changed_when: "'Pushed' in push_output.stdout or 'layer already exists' not in
        push_output.stdout"
