name: Build & Push Image

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      context:
        required: true
        type: string

env:
  AWS_ROLE_ARN: "arn:aws:iam::131912109503:role/GitHubActionsRole"
  AWS_ACCOUNT_ID: "131912109503"
  AWS_REGION: "us-east-2"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push
        run: |
          IMAGE=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/${{ inputs.repo_name }}
          docker build -t $IMAGE:${GITHUB_SHA::7} ${{ inputs.context }}
          docker push $IMAGE:${GITHUB_SHA::7}
