name: CI - Test & Build

on:
  push:
    branches: ["main"]
    paths:
      - backend/**
      - frontend/**
  workflow_dispatch:

env:
  AWS_ROLE_ARN: "arn:aws:iam::131912109503:role/GitHubActionsRole"
  AWS_ACCOUNT_ID: "131912109503"
  AWS_REGION: "us-east-2"
  FRONTEND_REPO: "onlytodo-frontend"
  BACKEND_REPO: "onlytodo-backend"

permissions:
  id-token: write
  contents: read

jobs:
  playwright_test:
    name: Run E2E Tests with Playwright
    runs-on: ubuntu-24.04
    container:
      image: mcr.microsoft.com/playwright:v1.50.0-noble # noble = ubuntu 24.04 base
    steps:
      - uses: actions/checkout@v6

      - name: Install Playwright
        working-directory: ./frontend/
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run Tests
        working-directory: ./frontend/
        run: |
          npm run test:e2e

      - uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: test-report
          path: ./frontend/results/
          retention-days: 1

  build_frontend:
    needs: playwright_test
    uses: ./.github/workflows/build-image.yml
    with:
      repo_name: onlytodo-frontend
      context: ./frontend

  build_backend:
    needs: playwright_test
    uses: ./.github/workflows/build-image.yml
    with:
      repo_name: onlytodo-backend
      context: ./backend
