name: Infra - Evening Teardown

on:
  workflow_dispatch:

env:
  AWS_ROLE_ARN: "arn:aws:iam::131912109503:role/GitHubActionsRole"
  PORKBUN_SECRET_ARN: "arn:aws:secretsmanager:us-east-2:131912109503:secret:todo-app-secrets-14Gg8G"
  AWS_REGION: "us-east-2"
  PARK_DOMAIN: "onlytodo.xyz.s3-website.us-east-2.amazonaws.com"

permissions:
  id-token: write
  contents: read

jobs:
  destroy_infrastructure:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.8"

      - name: Park Domain
        run: |
          echo "Fetching Porkbun Secrets..."
          PORKBUN_JSON=$(aws secretsmanager get-secret-value --secret-id $PORKBUN_SECRET_ARN --region $AWS_REGION --query SecretString --output text)
          export PORKBUN_API=$(echo $PORKBUN_JSON | jq -r .PORKBUN_API_KEY)
          export PORKBUN_SECRET=$(echo $PORKBUN_JSON | jq -r .PORKBUN_SECRET_KEY)

          echo "Updating DNS Record for ALB..."
          curl -X POST "https://api.porkbun.com/api/json/v3/dns/editByNameType/onlytodo.xyz/ALIAS" \
            -H "Content-Type: application/json" \
            -d "{ \"secretapikey\": \"$PORKBUN_SECRET\", \"apikey\": \"$PORKBUN_API\", \"content\": \"$PARK_DOMAIN\", \"ttl\": \"600\" }" \
            > /dev/null
          echo "Domain Parked Successfully."

      - name: EKS Ingress Cleanup
        run: |
          echo "Get kubeconfig for EKS cluster..."
          aws eks update-kubeconfig --region $AWS_REGION --name todo-cluster 2>/dev/null || true

          echo "Fetching ALB ARN before deletion..."
          ALB_DNS=$(kubectl get ingress todo-ingress --ignore-not-found -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')

          if [ -n "$ALB_DNS" ]; then
            echo "ALB DNS found: $ALB_DNS. Proceeding with cleanup..."
            ALB_ARN=$(aws elbv2 describe-load-balancers --query "LoadBalancers[?contains(DNSName, '$ALB_DNS')].LoadBalancerArn" --output text)

            echo "Forcing Finalizer removal to prevent pipeline hangs..."
            kubectl patch ingress todo-ingress -n default -p '{"metadata":{"finalizers":null}}' --type=merge 2>/dev/null || true

            echo "Deleting ingress resources..."
            kubectl delete -f ./k8s/eks/ingress.yml --ignore-not-found 2>/dev/null || true
            aws elbv2 delete-load-balancer --load-balancer-arn $ALB_ARN

            echo "Waiting for AWS to destroy the ALB..."
            aws elbv2 wait load-balancers-deleted --load-balancer-arns $ALB_ARN

            echo "ALB fully deleted from AWS! Clearing up..."
            sleep 30
          else
            echo "No ALB found in AWS. Skipping."
          fi

      - name: Terraform Destroy
        working-directory: iac/terraform/
        run: |
          terraform init
          terraform destroy -auto-approve
