name: Infra - Evening Teardown

on:
  workflow_dispatch:

env:
  AWS_ROLE_ARN: "arn:aws:iam::131912109503:role/GitHubActionsRole"
  PORKBUN_SECRET_ARN: "arn:aws:secretsmanager:us-east-2:131912109503:secret:OnlyToDo/Prod/All-rIjbxb"
  AWS_REGION: "us-east-2"
  PARK_DOMAIN: "onlytodo.xyz.s3-website.us-east-2.amazonaws.com"
  EKS_CLUSTER: "onlytodo"

permissions:
  id-token: write
  contents: read

jobs:
  park_domain:
    name: Park Domain on Porkbun
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Park Domain On Porkbun
        run: |
          PORKBUN_JSON=$(aws secretsmanager get-secret-value --secret-id $PORKBUN_SECRET_ARN --region $AWS_REGION --query SecretString --output text)
          export PORKBUN_API=$(echo $PORKBUN_JSON | jq -r .PORKBUN_API_KEY)
          export PORKBUN_SECRET=$(echo $PORKBUN_JSON | jq -r .PORKBUN_SECRET_KEY)

          curl -X POST "https://api.porkbun.com/api/json/v3/dns/editByNameType/onlytodo.xyz/ALIAS" \
            -H "Content-Type: application/json" \
            -d "{ \"secretapikey\": \"$PORKBUN_SECRET\", \"apikey\": \"$PORKBUN_API\", \"content\": \"$PARK_DOMAIN\", \"ttl\": \"600\" }"

          curl -X POST "https://api.porkbun.com/api/json/v3/dns/editByNameType/onlytodo.xyz/CNAME/*" \
            -H "Content-Type: application/json" \
            -d "{ \"secretapikey\": \"$PORKBUN_SECRET\", \"apikey\": \"$PORKBUN_API\", \"content\": \"pixie.porkbun.com\", \"ttl\": \"600\" }"

          echo -e "\nDomain Parked Successfully."

  destroy_infra:
    name: Destroy Infrastructure
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.8"

      - name: Configure kubectl
        run: aws eks update-kubeconfig --region "$AWS_REGION" --name "$EKS_CLUSTER"

      - name: Delete ArgoCD Applications
        run: |
          for app in onlytodo-frontend onlytodo-backend; do
            kubectl delete application $app -n argocd --ignore-not-found
          done

      - name: Delete Ingress
        run: |
          kubectl patch ingress onlytodo -p '{"metadata":{"finalizers":null}}' --type=merge
          kubectl delete ingress onlytodo --ignore-not-found

          ALB_ARN=$(aws elbv2 describe-load-balancers --names "onlytodo-shared-alb" --query "LoadBalancers[0].LoadBalancerArn" --output text)
          aws elbv2 delete-load-balancer --load-balancer-arn $ALB_ARN

      - name: Wait for ALB Removal
        run: |
          for i in $(seq 1 30); do
            ALB_DNS=$(kubectl get ingress onlytodo \
              --ignore-not-found \
              -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')

            if [ -z "$ALB_DNS" ]; then
              echo "Ingress gone. Confirming ALB deletion in AWS..."
              sleep 30
              break
            fi

            echo "Still waiting... ($((i * 10))s elapsed)"
            sleep 10

            if [ $i -eq 30 ]; then
              echo "ERROR: ALB not removed after 5 minutes. Aborting."
              exit 1
            fi
          done

      - name: Terraform Destroy
        working-directory: infra/terraform/
        run: |
          terraform init
          terraform state rm module.vpc.module.vpc.aws_vpc.this[0]
          terraform destroy -auto-approve

      - name: Cleaning Up VPC and Security Groups
        run: |
          VPC_ID=$(aws ec2 describe-vpcs \
            --filters "Name=tag:Name,Values=onlytodo" \
            --query 'Vpcs[0].VpcId' \
            --output text)
          SEC_GRP_ID1=$(aws ec2 describe-security-groups \
            --query "SecurityGroups[?GroupName!='default'].GroupId | [0]" \
            --output text)
          SEC_GRP_ID2=$(aws ec2 describe-security-groups \
            --query "SecurityGroups[?GroupName!='default'].GroupId | [1]" \
            --output text)

          aws ec2 delete-security-group --group-id $SEC_GRP_ID1
          aws ec2 delete-security-group --group-id $SEC_GRP_ID2
          aws ec2 delete-vpc --vpc-id $VPC_ID
