name: Infra - Evening Teardown

on:
  schedule:
    - cron: "33 17 * * *" # Evening: 17:30 PM BKK
      timezone: "Asia/Bangkok"
  workflow_dispatch:

env:
  AWS_ROLE_ARN: "arn:aws:iam::131912109503:role/GitHubActionsRole"
  AWS_REGION: "us-east-2"

permissions:
  id-token: write
  contents: read

jobs:
  destroy_infrastructure:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.8"

      - name: Terraform Destroy
        working-directory: iac/terraform/
        run: |
          terraform init
          terraform destroy -auto-approve
