name: Infra - Morning Startup

on:
  workflow_dispatch:

env:
  AWS_ROLE_ARN: "arn:aws:iam::131912109503:role/GitHubActionsRole"
  APP_SECRET_ARN: "arn:aws:secretsmanager:us-east-2:131912109503:secret:todo-app-secrets-14Gg8G"
  AWS_ACCOUNT_ID: "131912109503"
  AWS_REGION: "us-east-2"
  CORE_TABLE_NAME: "users"
  FRONTEND_REPO: "todo-frontend-repo"
  BACKEND_REPO: "todo-backend-repo"
  PROMETHEUS_REPO: "todo-prom-repo"
  GRAFANA_REPO: "todo-graf-repo"

permissions:
  id-token: write
  contents: read

jobs:
  initialize_infrastructure:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.8"

      - name: Terraform Init & Apply
        working-directory: iac/terraform/
        run: |
          terraform init
          terraform apply -auto-approve

  build_and_push_images:
    needs: [initialize_infrastructure]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Images
        run: |
          docker build --provenance=false -t $FRONTEND_REPO ./frontend/
          docker tag $FRONTEND_REPO:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$FRONTEND_REPO:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$FRONTEND_REPO:latest

          docker build --provenance=false -t $BACKEND_REPO ./backend/
          docker tag $BACKEND_REPO:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$BACKEND_REPO:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$BACKEND_REPO:latest

          docker build --provenance=false -t $PROMETHEUS_REPO ./mno/prometheus/
          docker tag $PROMETHEUS_REPO:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$PROMETHEUS_REPO:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$PROMETHEUS_REPO:latest

          docker build --provenance=false -t $GRAFANA_REPO ./mno/grafana/
          docker tag $GRAFANA_REPO:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$GRAFANA_REPO:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$GRAFANA_REPO:latest

  deploy_application:
    needs: [initialize_infrastructure]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive
          sudo apt-get update && sudo apt-get install -y jq
          curl -sL "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
          sudo dpkg -i session-manager-plugin.deb

          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --region $AWS_REGION --name todo-cluster

      - name: Add EKS Helm Repository
        run: |
          VPC_ID=$(aws ec2 describe-vpcs \
            --filters "Name=tag:Name,Values=todo-vpc" \
            --query 'Vpcs[0].VpcId' \
            --output text)

          helm repo add eks https://aws.github.io/eks-charts
          helm repo update
          helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
            -n kube-system \
            --set clusterName=todo-eks-cluster \
            --set serviceAccount.create=true \
            --set serviceAccount.name=aws-load-balancer-controller \
            --set region=$AWS_REGION \
            --set vpcId=$VPC_ID

      - name: Deploy Kubernetes Application
        run: |
          echo "Fetching Dynamic Secrets for K8s..."
          DB_SECRET_ARN=$(aws ssm get-parameter --name "/todo/config/db_secret_arn" --region $AWS_REGION --query "Parameter.Value" --output text)
          SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id $DB_SECRET_ARN --region $AWS_REGION --query SecretString --output text)
          export DB_PASS=$(echo $SECRET_JSON | jq -r .password)

          echo "Fetching JWT for backend K8s..."
          JWT_JSON=$(aws secretsmanager get-secret-value --secret-id $APP_SECRET_ARN --region $AWS_REGION --query SecretString --output text)
          export JWT_TOKEN=$(echo $JWT_JSON | jq -r .BACKEND_JWT_STRING)

          echo "Applying Manifests..."
          envsubst < k8s/eks/secrets.yml
          kubectl apply -f k8s/eks/

      - name: Wait for EKS ALB
        run: |
          echo "Waiting for AWS Load Balancer Controller to provision the ALB..."
          ALB_DNS=""
          # Loop up to 30 times (5 minutes) waiting for the ADDRESS column to populate
          for i in {1..30}; do
            # Extract the hostname dynamically from the ingress object
            ALB_DNS=$(kubectl get ingress todo-ingress -n default -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
            if [ -n "$ALB_DNS" ]; then
              echo "ALB provisioned successfully: $ALB_DNS"
              break
            fi
            echo "ALB not ready yet. Waiting 10 seconds..."
            sleep 10
          done

          if [ -z "$ALB_DNS" ]; then
            echo "Error: ALB failed to provision in time."
            exit 1
          fi

      - name: Update Porkbun DNS Record
        run: |
          echo "Fetching Porkbun Secrets..."
          PORKBUN_JSON=$(aws secretsmanager get-secret-value --secret-id $APP_SECRET_ARN --region $AWS_REGION --query SecretString --output text)
          PORKBUN_API=$(echo $PORKBUN_JSON | jq -r .PORKBUN_API_KEY)
          PORKBUN_SECRET=$(echo $PORKBUN_JSON | jq -r .PORKBUN_SECRET_KEY)

          echo "Updating DNS Record for ALB on Porkbun..."
          curl -X POST "https://api.porkbun.com/api/json/v3/dns/editByNameType/onlytodo.xyz/ALIAS" \
            -H "Content-Type: application/json" \
            -d "{\"secretapikey\":\"$PORKBUN_SECRET\", \"apikey\":\"$PORKBUN_API\", \"content\":\"$ALB_DNS\", \"ttl\": \"3600\"}"
          echo "EKS ALB DNS Updated Successfully."
